### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Fizcko** [AnaviTech/anavi-light-controller#4]
Hello,

Can this project support a 12v 3A input for a 10m RGB LED strip ?

I don't know if all electronics components can support up to 3A.

Thanks for the reply

**Comment by leon-anavi** [comment]
Hi @Fizcko,

ANAVI Light Controller uses IRF8721PBF/IRF8721TRPBF MOSFET for each of the 3 channels for the RGB light. According to the datasheet the Continuous Drain Current of each is up to 14A: https://www.mouser.bg/ProductDetail/Infineon-IR/IRF8721TRPBF

The traces on the boards are 20mils so in practice it is about 2.5Amps per channel and 60mils for the 12V trace. Depending on your setup it is also possible to wire the 12V for the RGB LED strip directory to the power adapter (and skip using the 12V trace on the board). It is also to use a DC barrel jack male adapter to a screw terminal. These adapters are quite popular because they are widely used for CCTV and can be found from many resellers, for example Sparkfun offers them: https://www.sparkfun.com/products/10287

**Comment by Fizcko** [comment]
@leon-anavi 

I didn't buy anything I'm studying the technical feasibility for the moment.

Thanks for the reply
